# hw-x2 spec - uses rlibc-x2 runtime
[cargo]
target_dir = "{name}-{hash}"

[linker]
args = ["-static", "-nostdlib", "-nodefaultlibs", "-e_start", "-Wl,--undefined=_start", "-Wl,--undefined=__libc_start_main"]
