[workspace]
members = ["rlibc-x1", "rlibc-x2", "rlibc-x2/tests", "app-x1", "app-x2", "app-hw-dl"]
resolver = "3"

[profile.dev]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
strip = false

[profile.release]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
strip = true
