[workspace]
members = ["rlibc-x1", "rlibc-x2", "rlibc-x2/tests", "apps/ex-x1", "apps/ex-x2", "apps/ex-glibc", "apps/ex-musl", "apps/hw-x1", "apps/hw-x2", "apps/hw-glibc", "apps/hw-musl"]
resolver = "3"

[profile.dev]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
strip = false

[profile.release]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
strip = true
