[workspace]
members = [
    "libs/rlibc-x1",
    "libs/rlibc-x2",
    "libs/rlibc-x2/tests",
    "apps/ex-x1",
    "apps/ex-x1-xt",
    "apps/ex-x2",
    "apps/ex-x2-xt",
    "apps/ex-glibc",
    "apps/ex-musl",
    "apps/hw-x1",
    "apps/hw-x2",
    "apps/hw-glibc",
    "apps/hw-musl",
    "tools/is-libc-used",
    "tools/func-analysis",
    "xtask",
    "xt",
]
resolver = "3"

# Minimize compile times for development
[profile.dev]
panic = "abort" # Required for rlibc-x1 as it's no-std

# Optimized for size
[profile.release]
panic = "abort"
opt-level = 'z'
lto = true
codegen-units = 1
debug = 2
debug-assertions = false
overflow-checks = false
incremental = false
strip = "none"

[profile.release-strip]
inherits = "release"
strip = "symbols"
