[alias]
b-musl = "build --target x86_64-unknown-linux-musl"
b-gnu = "build --target x86_64-unknown-linux-gnu"
r-musl = "run --target x86_64-unknown-linux-musl"
r-gnu = "run --target x86_64-unknown-linux-gnu"
