[alias]
xtask = "run --package xtask --"
xt = "run --package xt --"
b-musl = "build --target x86_64-unknown-linux-musl"
b-glibc = "build --target x86_64-unknown-linux-gnu"
r-musl = "run --target x86_64-unknown-linux-musl"
r-glibc = "run --target x86_64-unknown-linux-gnu"
t-musl = "test --target x86_64-unknown-linux-musl"
t-glibc = "test --target x86_64-unknown-linux-gnu"
