[package]
name = "ex-x2"
version = "0.1.0"
edition = "2024"
description = "Minimal exit-only binary using rlibc-x2 (std with custom libc)"

[dependencies]
rlibc-x2 = { path = "../../rlibc-x2" }

[dev-dependencies]
is-libc-used = { path = "../../tools/is-libc-used" }

[[bin]]
name = "ex-x2"
test = false
